/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.nothings.stb.image;

public class LibraryTest {
/*    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }*/
}
